# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(13, 50, 541, 131))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setLineWidth(3)
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 511, 31))
        self.label.setObjectName("label")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(480, 210, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.three.setFont(font)
        self.three.setObjectName("three")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(390, 300, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.five.setFont(font)
        self.five.setObjectName("five")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(390, 210, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.two.setFont(font)
        self.two.setObjectName("two")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(480, 300, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.six.setFont(font)
        self.six.setObjectName("six")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(390, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.eight.setFont(font)
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(480, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nine.setFont(font)
        self.nine.setObjectName("nine")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(300, 210, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.one.setFont(font)
        self.one.setObjectName("one")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(300, 300, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.four.setFont(font)
        self.four.setObjectName("four")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(300, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.seven.setFont(font)
        self.seven.setObjectName("seven")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(390, 470, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.zero.setFont(font)
        self.zero.setObjectName("zero")
        self.POW = QtWidgets.QPushButton(self.centralwidget)
        self.POW.setGeometry(QtCore.QRect(20, 190, 151, 41))
        self.POW.setObjectName("POW")
        self.SQRT = QtWidgets.QPushButton(self.centralwidget)
        self.SQRT.setGeometry(QtCore.QRect(180, 190, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SQRT.setFont(font)
        self.SQRT.setObjectName("SQRT")
        self.factorial = QtWidgets.QPushButton(self.centralwidget)
        self.factorial.setGeometry(QtCore.QRect(180, 240, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.factorial.setFont(font)
        self.factorial.setObjectName("factorial")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 360, 261, 151))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.Plus = QtWidgets.QPushButton(self.centralwidget)
        self.Plus.setGeometry(QtCore.QRect(20, 240, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Plus.setFont(font)
        self.Plus.setObjectName("Plus")
        self.Minus = QtWidgets.QPushButton(self.centralwidget)
        self.Minus.setGeometry(QtCore.QRect(100, 240, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Minus.setFont(font)
        self.Minus.setObjectName("Minus")
        self.Umnozh = QtWidgets.QPushButton(self.centralwidget)
        self.Umnozh.setGeometry(QtCore.QRect(20, 300, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Umnozh.setFont(font)
        self.Umnozh.setObjectName("Umnozh")
        self.Delenie = QtWidgets.QPushButton(self.centralwidget)
        self.Delenie.setGeometry(QtCore.QRect(100, 300, 51, 41))
        self.Delenie.setObjectName("Delenie")
        self.Equals = QtWidgets.QPushButton(self.centralwidget)
        self.Equals.setGeometry(QtCore.QRect(180, 300, 51, 41))
        self.Equals.setObjectName("Equals")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 470, 71, 51))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">КАЛЬКУЛЯТОР 1.0</span></p></body></html>"))
        self.three.setText(_translate("MainWindow", "3"))
        self.five.setText(_translate("MainWindow", "5"))
        self.two.setText(_translate("MainWindow", "2"))
        self.six.setText(_translate("MainWindow", "6"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.one.setText(_translate("MainWindow", "1"))
        self.four.setText(_translate("MainWindow", "4"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.POW.setText(_translate("MainWindow", "Возведение в степень"))
        self.SQRT.setText(_translate("MainWindow", "√"))
        self.factorial.setText(_translate("MainWindow", "!"))
        self.Plus.setText(_translate("MainWindow", "+"))
        self.Minus.setText(_translate("MainWindow", "-"))
        self.Umnozh.setText(_translate("MainWindow", "*"))
        self.Delenie.setText(_translate("MainWindow", "/"))
        self.Equals.setText(_translate("MainWindow", "="))
        self.pushButton.setText(_translate("MainWindow", "RESET"))

